name: Tauri Dev Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Setup system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            cmake \
            g++

      - name: Build backend
        run: |
          cd backend
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
          cp bin/docutrace-backend ../../apps/tauri/src-tauri/binaries/docutrace-backend-x86_64-unknown-linux-gnu

      - name: Build frontend
        run: |
          cd apps/tauri
          pnpm build

      - name: Build Tauri app
        run: |
          cd apps/tauri
          cargo tauri build

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: docutrace-linux-dev
          path: apps/tauri/src-tauri/target/debug/bundle/
          retention-days: 7 