name: Tauri Dev Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('apps/tauri/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd apps/tauri
          pnpm install

      - name: Setup system dependencies (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            cmake \
            g++

      - name: Setup vcpkg (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install crow:x64-linux openssl:x64-linux zlib:x64-linux nlohmann-json:x64-linux

      - name: Setup vcpkg (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install crow:x64-windows openssl:x64-windows zlib:x64-windows nlohmann-json:x64-windows

      - name: Build backend (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          cd backend
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          make -j$(nproc)
          cp bin/docutrace-backend ../../apps/tauri/src-tauri/binaries/docutrace-backend-x86_64-unknown-linux-gnu

      - name: Build backend (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          cd backend
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build . --config Release
          copy bin\Release\docutrace-backend.exe ..\..\apps\tauri\src-tauri\binaries\docutrace-backend-x86_64-pc-windows-msvc.exe

      - name: Build frontend
        run: |
          cd apps/tauri
          pnpm build

      - name: Instalar CLI de Tauri (Rust)
        run: cargo install tauri-cli --version ^2

      - name: Build Tauri app
        run: |
          cd apps/tauri
          cargo tauri build -- --release

      - name: Upload artifact (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: docutrace-linux-dev
          path: apps/tauri/src-tauri/target/debug/bundle/
          retention-days: 7

      - name: Upload artifact (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: docutrace-windows-dev
          path: apps/tauri/src-tauri/target/debug/bundle/
          retention-days: 7
